In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv("dataset/house.csv")

In [10]:
data.head()#first 5 rows

,Unnamed: 0,price,lotSize,age,landValue,livingArea,pctCollege,bedrooms,fireplaces,bathrooms,rooms,heating,fuel,sewer,waterfront,newConstruction,centralAir
0,1,132500,0.09,42,50000,906,35,2,1,1.0,5,electric,electric,septic,No,No,No
1,2,181115,0.92,0,22300,1953,51,3,0,2.5,6,hot water/steam,gas,septic,No,No,No
2,3,109000,0.19,133,7300,1944,51,4,1,1.0,8,hot water/steam,gas,public/commercial,No,No,No
3,4,155000,0.41,13,18700,1944,51,3,1,1.5,5,hot air,gas,septic,No,No,No
4,5,86060,0.11,0,15000,840,51,2,0,1.0,3,hot air,gas,public/commercial,No,Yes,Yes

In [11]:
data.tail(5)#last 5

,Unnamed: 0,price,lotSize,age,landValue,livingArea,pctCollege,bedrooms,fireplaces,bathrooms,rooms,heating,fuel,sewer,waterfront,newConstruction,centralAir
1723,1724,289000,0.38,32,24200,2310,61,5,1,2.5,11,hot water/steam,gas,public/commercial,No,No,No
1724,1725,285000,0.94,37,36200,2564,61,4,1,2.5,11,hot water/steam,gas,public/commercial,No,No,No
1725,1726,194900,0.39,9,20400,1099,51,2,0,1.0,3,hot air,gas,public/commercial,No,No,No
1726,1727,125000,0.24,48,16800,1225,51,3,1,1.0,7,hot air,gas,public/commercial,No,No,No
1727,1728,111300,0.59,86,26000,1959,51,3,0,1.0,6,hot air,gas,septic,No,No,No

In [14]:
x = data['livingArea']
y = data['price']
print(len(x))
print(len(y))

1728
1728

In [13]:
mean_x = np.mean(x)
mean_y = np.mean(y)

In [15]:
num = 0
for i in range(len(x)):
    num += (x[i]-mean_x)*(y[i]-mean_y)

deno = 0
for i in range(len(x)):
    deno += (x[i]-mean_x)**2

B1 = num/deno

In [16]:
B1

np.float64(113.1225418468094)

In [17]:
B0 = mean_y - B1*mean_x

In [18]:
B0,B1

(np.float64(13439.394004889764), np.float64(113.1225418468094))

In [19]:
#prediction
newX = 906
Y_pred = B0+B1*newX

In [ ]:
Y_pred

np.float64(115928.41691809907)

In [21]:
y[0]

np.int64(132500)

In [24]:
error =  y[0]-Y_pred

In [25]:
error

np.float64(16571.583081900928)

In [ ]:
#optimization technique- gradient DESCENT